title: CodeChimp
email: andrew@codechimp.org
# description: >- # this means to ignore newlines until "baseurl:"
#   Productivity Apps & Tools
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://codechimp.org" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: andrewcodechimp
github_username:  andrew-codechimp
# mastodon:
# - username: codechimp
#   instance: mastodon.online

# Build settings
theme: minima

permalink: /:title/

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-seo-tag
  
sass:
  sass_dir: _sass

author:    
  name: Andrew Jackson    
  email: andrew@codechimp.org
